cap_text.c: fix 'asprintf' inplicit declaration
Detected by gcc:
  cap_text.c: In function 'cap_to_name':
  cap_text.c:291:2: warning: implicit declaration of function 'asprintf';
      did you mean 'vsprintf'? [-Wimplicit-function-declaration]
    asprintf(&tmp, "%u", cap);
    ^~~~~~~~
    vsprintf

In order to get 'asprintf' declaration '_GNU_SOURCE' needs to be defined
before '<stdio.h>' in included.

'cap_text.c' injects '<stdio.h>' include as '-include _caps_output.gperf'
(via '<string.h>') before '_GNU_SOURCE' is defined in source file.

The change moves '_caps_output.gperf' inclusion after '_GNU_SOURCE'
declaration.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>